### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by MustaphaTR** [MustaphaTR/sole-survivor#1]
* [ ] Add units from TD that SS didn't have
* * [x] Engineer:
* * * [ ] Towers should be affected from Damage/Range/RoF bonuses.
* * [x] Harvester:
* * [ ] MCV:
* * [ ] Mobile HQ:
* * * [ ] Will start with Free Radar.
* * [ ] Chinook:
* * * [ ] Requires crate rework so they can collect them.
* * [ ] Orca:
* * * [ ] Requires crate rework so they can collect them.
* * [ ] Apache:
* * * [ ] Requires crate rework so they can collect them.

* [ ] Add original crates.
* * [x] Brown:
* * * [ ] Stealth crate should be on/off rather than timed.
* * [x] Green:
* * [x] Silver:
* * * [ ] Bonuses should be more effective than brown ones.
* * [ ] Orange:
* * [ ] Red:

* [ ] Teleporters.
* [ ] Rebalance stuff for better gameplay.
